NDefines.NGame.START_DATE = "2024.1.1.12";
NDefines.NGame.END_DATE = "2045.1.1.1";
NDefines.NGame.MAP_SCALE_PIXEL_TO_KM = 4.096;
NDefines.NGraphics.COUNTRY_COLOR_SATURATION_MODIFIER = 0.8;
NDefines.NGraphics.COUNTRY_COLOR_BRIGHTNESS_MODIFIER = 0.9;